# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDto',
            fields=[
                ('seasonId', models.IntegerField()),
                ('queueId', models.IntegerField()),
                ('gameId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('gameVersion', models.CharField(max_length=30)),
                ('platformId', models.CharField(max_length=10)),
                ('gameMode', models.CharField(max_length=30)),
                ('mapId', models.IntegerField()),
                ('gameType', models.CharField(max_length=20)),
                ('gameDuration', models.BigIntegerField()),
                ('gameCreation', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantIdentityDto',
            fields=[
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participantIdentities', serialize=False, to='search.MatchDto')),
                ('participantId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatsDto',
            fields=[
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teams', serialize=False, to='search.MatchDto')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDto',
            fields=[
                ('participantIdentity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player', serialize=False, to='search.ParticipantIdentityDto')),
                ('currentPlatformId', models.CharField(max_length=10)),
                ('summonerName', models.CharField(max_length=16)),
                ('matchHistoryUri', models.CharField(max_length=50)),
                ('platformId', models.CharField(max_length=10)),
                ('currentAccountId', models.BigIntegerField()),
                ('profileIcon', models.IntegerField()),
                ('summonerId', models.BigIntegerField()),
                ('accountId', models.BigIntegerField()),
            ],
        ),
    ]
