# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20171123_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('gameId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('jsonString', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='participantidentitydto',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playerdto',
            name='participantIdentity',
        ),
        migrations.RemoveField(
            model_name='teamstatsdto',
            name='match',
        ),
        migrations.DeleteModel(
            name='MatchDto',
        ),
        migrations.DeleteModel(
            name='ParticipantIdentityDto',
        ),
        migrations.DeleteModel(
            name='PlayerDto',
        ),
        migrations.DeleteModel(
            name='TeamStatsDto',
        ),
    ]
