# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20171123_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTimeline',
            fields=[
                ('gameId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('jsonString', models.TextField()),
            ],
        ),
    ]
